### ISSUE TITLE
Help Option does not work for top-level help

### ISSUE THREAD

**Issue by agc93** [spectresystems/spectre.commandline#11]
Running a Spectre-enabled app without any arguments shows the help text and available commands. Likewise, running an individual command with the help switches set in `SetHelpOption` shows the help for the command.

However, I would expect that using the same option (from `SetHelpOption`) with the top-level executable should also display available commands etc, same as running without any arguments does.

That is, I would say that running:

```
MyConsoleApp
```
and

```
MyConsoleApp --help
```

...should give the same output.

Sample repo included [here](https://github.com/agc93/spectre-cli-demo)

**Comment by patriksvensson** [comment]
Resolved in version 0.6.0.
