### ISSUE TITLE
[Question] How to add commands and arguments programmatically?

### ISSUE THREAD

**Issue by DoCode** [spectresystems/spectre.commandline#18]
How can commands and arguments add programmatically to the CommandApp?

**Comment by patriksvensson** [comment]
@DoCode What do you mean by programmatically? Dynamically?

**Comment by DoCode** [comment]
@patriksvensson Yes, my requirement is to load commands and arguments from a JSON file and create the CommandApp dynamically at runtime. Then add the args and so on...

**Comment by patriksvensson** [comment]
@DoCode Nothing that is supported OOTB, and I don't think we will add something like it.

However, nothing should stop you from building the command application dynamically yourself with some reflection magic. I'm busy with work at the moment, but I can help you out when I have some free time.

**Comment by patriksvensson** [comment]
@DoCode Did you solve this or do you want some help?
