### ISSUE TITLE
Required argument syntax is opposite to Unix conventions

### ISSUE THREAD

**Issue by agc93** [spectresystems/spectre.commandline#9]
From what I can tell, [this code](https://github.com/spectresystems/spectre.commandline/blob/master/src/Spectre.CommandLine/Annotations/ArgumentAttribute.cs#L43) means that any argument represented as `[arg-name]` will be required while any arg in the format `<arg-name>` will be accepted but made optional.

This is the exact opposite of the [usual convention](https://en.wikipedia.org/wiki/Command-line_interface#Command_description_syntax) for Unix-like environments. Is this something that would be changeable, or configurable?

**Comment by patriksvensson** [comment]
Fixed.
